# Generated by Django 6.0.6 on 2026-06-08 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='clinica',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.clinica'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('administrador', 'Admin'), ('recepção', 'Recepcao'), ('clínico', 'Clinico'), ('auxiliar', 'Auxiliar')], max_length=13),
        ),
    ]
