# Generated by Django 6.0.6 on 2026-06-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuario_is_staff_usuario_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='endereco',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('administrador', 'Admin'), ('recepção', 'Recepcao'), ('clínico', 'Clinico'), ('auxiliar', 'Auxiliar')], default='clínico', max_length=13),
        ),
    ]
