# Generated by Django 6.0.6 on 2026-06-09 18:24

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_clinica_endereco_alter_usuario_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='telefone',
            field=models.CharField(max_length=13, validators=[apps.accounts.validators.validate_phone]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=13, null=True, unique=True, validators=[apps.accounts.validators.validate_phone]),
        ),
    ]
