# Generated by Django 6.0.6 on 2026-06-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_clinica_telefone_alter_usuario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('administrador', 'Admin'), ('recepcionista', 'Recepcionista'), ('clínico', 'Clinico'), ('auxiliar', 'Auxiliar')], default='clínico', max_length=13),
        ),
    ]
