# Generated by Django 6.0.6 on 2026-06-13 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_usuario_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='clinica',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.clinica'),
        ),
    ]
