# Generated by Django 6.0.6 on 2026-06-13 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_usuario_clinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.clinica'),
        ),
    ]
