class EvolutionAPIException(Exception): ...


class InstanciaWhatsAppJaExiste(EvolutionAPIException): ...


class InstanciaWhatsAppNaoEncontrada(EvolutionAPIException): ...


class EvolutionAPINaoConfigurada(EvolutionAPIException): ...


class EvolutionAPIRespostaInvalida(EvolutionAPIException): ...
