# Generated by Django 6.0.6 on 2026-06-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatsappinstance',
            old_name='instance_id',
            new_name='instancia_id',
        ),
    ]
