# Generated by Django 6.0.6 on 2026-06-09 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_clinica_telefone_alter_usuario_telefone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('duracao', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ativo', models.BooleanField(default=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('agendado', 'Agendado'), ('cancelado', 'Cancelado'), ('concluído', 'Concluido')], default='pendente', max_length=15)),
                ('observacoes', models.TextField(null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('clinico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.procedimento')),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda'), (2, 'Terca'), (3, 'Quarta'), (4, 'Quinta'), (5, 'Sexta'), (6, 'Sabado')])),
                ('inicio', models.TimeField()),
                ('fim', models.TimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('clinico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ativo', 'clinico', 'dia')},
            },
        ),
        migrations.AddConstraint(
            model_name='procedimento',
            constraint=models.CheckConstraint(condition=models.Q(('duracao__gte', 1)), name='duracao_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='procedimento',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gte', 1)), name='valor_gte_1'),
        ),
        migrations.AlterUniqueTogether(
            name='procedimento',
            unique_together={('nome', 'clinica')},
        ),
    ]
