# Generated by Django 6.0.6 on 2026-06-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='dia',
            field=models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda'), (2, 'Terça'), (3, 'Quarta'), (4, 'Quinta'), (5, 'Sexta'), (6, 'Sábado')]),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='duracao',
            field=models.PositiveIntegerField(),
        ),
    ]
