# Generated by Django 6.0.6 on 2026-06-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_expediente_dia_alter_procedimento_duracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='dia',
            field=models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')]),
        ),
    ]
