# Generated by Django 6.0.6 on 2026-06-13 13:11

import apps.accounts.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_usuario_cargo'),
        ('agenda', '0003_alter_expediente_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('agendado', 'Agendado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluido')], default='pendente', max_length=15),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('sobrenome', models.CharField(max_length=128)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(max_length=13, unique=True, validators=[apps.accounts.validators.validate_phone])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.clinica')),
            ],
        ),
        migrations.AddField(
            model_name='agendamento',
            name='paciente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='agenda.paciente'),
            preserve_default=False,
        ),
    ]
