# Generated by Django 6.0.6 on 2026-06-13 13:45

import apps.agenda.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_agendamento_status_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[apps.agenda.validators.validate_cpf]),
        ),
    ]
